/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms.inventario;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ing.Ivan
 */
public class Inventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModificarProducto
     */
    public Inventario() {
        initComponents();
        setResizable(false);
        txt_buscar.requestFocus();
        DesactivarCampos();
    }

    public void DesactivarCampos() {
        /*txtCodigo.setEnabled(false);
        txtDescri.setEnabled(false);
        txtPrecio.setEnabled(false);
        txtExistencia.setEnabled(false);
        btn_guardar.setEnabled(false);
        btncancelar.setEnabled(false);*/
    }

    //metodo donde crea la tabla de productos 
    DefaultTableModel m;

    public void TablaProducto(String val) {//Realiza la consulta de los productos que tenemos en la base de datos
        String titles[] = {"Codigo", "Descripción", "Precio", "Existencia"};
        String reg[] = new String[5];
        String sentence = "";
        m = new DefaultTableModel(null, titles);

        Connection con;
        con = conexion.Conexion.GetConnection();
        sentence = "CALL SP_ProductosSel('%" + val + "%')";

        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sentence);
            while (rs.next()) {
                reg[0] = rs.getString("prod_codigo");
                reg[1] = rs.getString("prod_descri");
                reg[2] = rs.getString("prod_precio");
                reg[3] = rs.getString("prod_existencia");
                m.addRow(reg);//agrega el registro a la tabla
            }
            TablaSqlProducto.setModel(m);//asigna a la tabla el modelo creado

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    //metodo donde obtiene los datos de la tabla para despues modificarlos
    String id_act = "";

    public void Buscar_editar(String val) {
        Connection con = conexion.Conexion.GetConnection();
        String sentence = "";
        String idp = "", descrip = "", precp = "", exisp = "";
        sentence = "CALL SP_ProductosSel('%" + val + "%')";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sentence);
            while (rs.next()) {
                idp = rs.getString("prod_codigo");
                descrip = rs.getString("prod_descri");
                precp = rs.getString("prod_precio");
                exisp = rs.getString("prod_existencia");

                /*txtCodigo.setText(idp);
                txtDescri.setText(descrip);
                txtPrecio.setText(precp);
                txtExistencia.setText(exisp);*/

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    //metodo donde llena los capos al seleccionar una fila
    String action = "Insertar";

    public void seleccionarfilamodificar() {
        int filasel;
        String id;
        try {
            filasel = TablaSqlProducto.getSelectedRow();
            if (filasel == -1) {
                JOptionPane.showMessageDialog(null, "No se ha seleccionado ninguna fila", "Advertencia", JOptionPane.WARNING_MESSAGE);
                txt_buscar.requestFocus();
            } else {
                //txtCodigo.setEnabled(true);
                /*txtDescri.setEnabled(true);
                //boxEmpresa.setEnabled(true);
                txtExistencia.setEnabled(true);
                txtPrecio.setEnabled(true);
                btn_guardar.setEnabled(true);
                btncancelar.setEnabled(true);*/

                txt_buscar.setText("");
                TablaSqlProducto.setVisible(false);
                action = "Modificar";
                m = (DefaultTableModel) TablaSqlProducto.getModel();
                id = (String) m.getValueAt(filasel, 0);
                System.out.println("Id mandado para modificar" + id);
                Buscar_editar(id);
                TablaProducto("");
                txt_buscar.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaSqlProducto = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        btnok = new javax.swing.JButton();
        lbBanner = new javax.swing.JLabel();

        setBackground(new java.awt.Color(45, 62, 80));
        setClosable(true);
        setIconifiable(true);
        setTitle("Ventana Inventario");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(1211, 636));

        jPanel3.setBackground(new java.awt.Color(45, 62, 80));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, new java.awt.Color(0, 0, 0)), "Inventario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sitka Subheading", 1, 36), new java.awt.Color(0, 204, 204))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos40x40/40x40-BUSCAR.png"))); // NOI18N
        jLabel10.setText("  BUSCAR ");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 102)));
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, 40));

        txt_buscar.setBackground(new java.awt.Color(0, 0, 0));
        txt_buscar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txt_buscar.setForeground(new java.awt.Color(0, 204, 204));
        txt_buscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_buscar.setCaretColor(new java.awt.Color(0, 204, 204));
        txt_buscar.setDisabledTextColor(new java.awt.Color(0, 204, 204));
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });
        jPanel3.add(txt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 570, 40));

        TablaSqlProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, new java.awt.Color(102, 102, 102)));
        TablaSqlProducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TablaSqlProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "HALEY", null, null, null, null, "3", "2", null, null, null},
                {"2", null, null, null, null, null, null, null, null, null, null},
                {"3", null, null, null, null, null, null, null, null, null, null},
                {"4", null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Producto", "Presentación", "Fecha primera entrada", "Fecha última entrada", "Fecha última salida", "Cantidad entradas", "Cantidad salidas", "Precio promedio", "Costo total", "Cantidad total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaSqlProducto.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TablaSqlProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TablaSqlProducto.setOpaque(false);
        TablaSqlProducto.getTableHeader().setReorderingAllowed(false);
        TablaSqlProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaSqlProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaSqlProducto);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1180, 320));

        btnok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventario/aceptar.png"))); // NOI18N
        btnok.setToolTipText("Eliminar Fila Seleccionada");
        btnok.setBorderPainted(false);
        btnok.setContentAreaFilled(false);
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });
        jPanel3.add(btnok, new org.netbeans.lib.awtextra.AbsoluteConstraints(932, 193, -1, -1));

        lbBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Forms/Banners/bannertabla.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lbBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbBanner)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        getAccessibleContext().setAccessibleName("Inventario");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void Limpiar() {
        /*txtCodigo.setText("");
        txtDescri.setText("");
        txtPrecio.setText("");
        txtExistencia.setText("");
        txt_buscar.requestFocus();

        txtCodigo.setEnabled(false);
        txtDescri.setEnabled(false);
        txtPrecio.setEnabled(false);
        txtExistencia.setEnabled(false);
        btn_guardar.setEnabled(false);
        btncancelar.setEnabled(false);*/
    }
    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased
        //actualiza la tabla conforme a la letra que teclea
        if (txt_buscar.getText().trim().length() >= 1) {
            String filtro = txt_buscar.getText();
            TablaProducto(filtro);
            TablaSqlProducto.setVisible(true);
        } else {
            TablaSqlProducto.setVisible(false);
        }
    }//GEN-LAST:event_txt_buscarKeyReleased

    private void TablaSqlProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaSqlProductoMouseClicked
        if (evt.getClickCount() == 2) {
            seleccionarfilamodificar();
        }
    }//GEN-LAST:event_TablaSqlProductoMouseClicked

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        seleccionarfilamodificar();
    }//GEN-LAST:event_btnokActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaSqlProducto;
    private javax.swing.JButton btnok;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBanner;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
